use DEMO

-- CONCAT SUBSTRING REPLACE LEFT RIGHT REPLICATE REVERSE STUFF
CREATE VIEW V_CustomerNamesAndPaymentNumbers AS
SELECT FirstName,
 LOWER(LastName),
LEFT(PaymentNumber,6) + REPLICATE('*', LEN(PaymentNumber) -6) AS 
CCCNumber
 FROM Customers

 SELECT * FROM V_CustomerNamesAndPaymentNumbers

 SELECT CHARINDEX('UNI', 'SOFTUNI',1)
 SELECT SUBSTRING('SOFTUNISAGEW',2, 40) +'S'	AS SAD

 SELECT STUFF ( 'SoftUni',5,0, 'test')

SELECT STUFF ( 'SoftUni',CHARINDEX('Uni','SoftUnit'),0, 'test')

SELECT A,H,(A*H)/2 AS AREA FROM Triangles2

-- ABS SQRT SQUARE POWER ROUND SIGN FLOOR CEILING 
--RAND() FROM [0;1)

SELECT * FROM INFORMATION_SCHEMA.TABLES

SELECT SQRT(SQUARE(X1-X2) + SQUARE(Y1-Y2)) AS [Length]
FROM Lines

SELECT ROUND(155.535, -1)
SELECT FLOOR(155.55)
SELECT CEILING(155.55)
SELECT SIGN(-4)

--DATE FUNCTIONS  DATEPART  DATEDIF DATENAME DATEADD

SELECT DATEPART(MONTH, '5-11-2018')

USE Orders


SELECT DATEPART(QUARTER,OrderDate) as Quarter,
DATEPART(MONTH, OrderDate) AS Month ,
DATEPART(year, OrderDate) as Year,
DATEPART(DAY, OrderDate) as Day,
OrderDate
FROM Orders

SELECT DATEDIFF(DAY, '12-10-2017', '1-4-2018')

 USE SoftUni

 SELECT EmployeeID,
		 CONCAT(FirstName,' ',LastName) as [Name],
		 DATEDIFF(YEAR,HireDate, GETDATE()) AS ExperienceMonths  
 FROM Employees

SELECT DATENAME(WEEKDAY, '11-13-2016')

SELECT FORMAT(DATEADD(MONTH, 1, '11-12-2016'), 'dd-MMM-yyyy')

-- OTHER FUNNCTIONS
-- CAST CONVERT FETCH ISNULL
SELECT CAST (12.3231231 AS int)

select CONVERT(DATE, '12-11-2016', 103)	 
SELECT ISNULL('DASDAS','')

SELECT * FROM Employees
ORDER BY EmployeeID
OFFSET 50 ROWS
FETCH NEXT 5 ROWS ONLY

SELECT EmployeeID,FirstName,LastName 
FROM Employees
WHERE LastName LIKE '%OV'

SELECT EmployeeID,FirstName,LastName 
FROM Employees
WHERE FirstName LIKE '__UL%'

SELECT EmployeeID,FirstName,LastName 
FROM Employees
WHERE FirstName LIKE'[PA]%'
 --'[^PA]%'
ORDER BY FirstName